package edu.byu.ece.rapidSmith.timing.routing;

public enum WireDimension {
    CLEXL_Length,
    CLEXL_Width,
    CLEXL_Start,
    CLEXL_End,
    CLEXL_Internal,
    CLEXM_Length,
    CLEXM_Width,
    CLEXM_Start,
    CLEXM_End,
    CLEXM_Internal,
    INT_Length,  
    INT_Width,   
    INT_Start,   
    INT_End,     
    INT_Internal,
    BIOI_INNER_Length,  
    BIOI_INNER_Width,   
    BIOI_INNER_Start,   
    BIOI_INNER_End,     
    BIOI_INNER_Internal,
    BIOI_OUTER_Length,  
    BIOI_OUTER_Width,   
    BIOI_OUTER_Start,   
    BIOI_OUTER_End,     
    BIOI_OUTER_Internal,
    BIOB_Length,  
    BIOB_Width,   
    BIOB_Start,   
    BIOB_End,     
    BIOB_Internal,
    IOI_INT_Length,  
    IOI_INT_Width,   
    IOI_INT_Start,   
    IOI_INT_End,     
    IOI_INT_Internal,
    Other_Length,
    Other_Width,
    Other_Start,
    Other_End,
    Other_Internal,
    PassTransistor

}
